server:
  port: 1000
  servlet:
    context-path: /customer-service


spring:
  application:
    name: customer-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true



