server:
  port: 2000
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

