#server config
server:
  port: 1000
  servlet:
    context-path: /customer-service

spring:
  application:
    name: customer-service
#zipkin server config
  zipkin:
    base-url: http://localhost:9411

  #datasource config
  datasource:
    username: root
    password: 1234
    data-source-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unicoin_customer_service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


#eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true




