server:
  port: 2000
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service
  #zipkin config
  zipkin:
    base-url: http://localhost:9411
  #rabbitmq config
  rabbitmq:
    addresses: localhost:5672
  #datasource config
  datasource:
    hikari:
      username: root
      password: 1234
      data-source-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/uniocoin_product_service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

#eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

