server:
  port: 2000
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service
  #zipkin config
  zipkin:
    base-url: http://localhost:9411
  #rabbitmq config
  rabbitmq:
    addresses: localhost:5672
  #datasource config
  datasource:
    username: root
    password: Unicoin123
    data-source-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unicoin_product_service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

