#server config
server:
  port: 8888
  servlet:
    context-path: /login-service

spring:
  application:
    name: login-service
  #datasource config
  datasource:
    username: root
    password: Unicoin123
    data-source-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unicoin_customer_service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
