CREATE TABLE `OPTIONS`
(
    `OPTION_ID`    int          NOT NULL AUTO_INCREMENT,
    `PRODUCT_ID` INT NOT NULL,
    `OPTION_CODE` VARCHAR(255) ,
    `OPTION_NAME`  varchar(255) ,
    `status`       INT,
    PRIMARY KEY (`OPTION_ID`),
    CONSTRAINT `FK_OPTION_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci