CREATE TABLE `OPTIONS`
(
    `OPTION_ID`    int          NOT NULL AUTO_INCREMENT,
    `OPTION_CODE` VARCHAR(255) NOT NULL ,
    `OPTION_NAME`  varchar(255) NOT NULL,
    `status`       INT     NOT NULL,
    PRIMARY KEY (`OPTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci