CREATE TABLE `OPTION_VALUES`(
    `OPTION_VALUE_ID` INT NOT NULL AUTO_INCREMENT,
    `OPTION_ID` INT NOT NULL,
    `OPTION_VALUE` VARCHAR(10000) ,
    `STATUS` INT ,
    PRIMARY KEY (`OPTION_VALUE_ID`),
    CONSTRAINT `FK_OPTIONS` FOREIGN KEY (`OPTION_ID`) REFERENCES `OPTIONS` (`OPTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci