CREATE TABLE `PRODUCT_OPTIONS`
(
    `OPTION_ID`    int NOT NULL,
    `PRODUCT_ID`  INT NOT NULL,
    PRIMARY KEY (`OPTION_ID`, `PRODUCT_ID`),
    CONSTRAINT `FK_PRODUCT_OPTIONS_OPTIONS` FOREIGN KEY (`OPTION_ID`) REFERENCES `OPTIONS` (`OPTION_ID`),
    CONSTRAINT `FK_PRODUCT_OPTIONS_PRODUCTS` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci