CREATE TABLE `OPTION_LIST`
(
    `OPTION_ID`    int          NOT NULL AUTO_INCREMENT,
    `OPTION_CODE` VARCHAR(255) ,
    `OPTION_NAME`  varchar(255) ,
    PRIMARY KEY (`OPTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci