CREATE TABLE `products` (
                            `product_id` int NOT NULL AUTO_INCREMENT,
                            `color_id` int NOT NULL,
                            `size_id` int NOT NULL,
                            `supplier_id` int NOT NULL,
                            `commodity_id` int NOT NULL,
                            `cost` double NOT NULL DEFAULT '0',
                            `price` double NOT NULL DEFAULT '0',
                            `quantity` int NOT NULL,
                            `code_product` varchar(45) NOT NULL,
                            `regist_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            `update_user` varchar(45) NOT NULL,
                            `del_flg` varchar(45) NOT NULL,
                            `status` tinyint NOT NULL,
                            PRIMARY KEY (`product_id`),
                            KEY `fk_color_product_idx` (`color_id`),
                            KEY `fk_size_product_idx` (`size_id`),
                            KEY `fk_commodity_product_idx` (`commodity_id`),
                            KEY `fk_supplier_product_idx` (`supplier_id`),
                            CONSTRAINT `fk_color_product` FOREIGN KEY (`color_id`) REFERENCES `colors` (`color_id`),
                            CONSTRAINT `fk_commodity_product` FOREIGN KEY (`commodity_id`) REFERENCES `commodities` (`commodity_id`),
                            CONSTRAINT `fk_size_product` FOREIGN KEY (`size_id`) REFERENCES `size_id` (`size_id`),
                            CONSTRAINT `fk_supplier_product` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`supplier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci