
# insert table suppliers
INSERT INTO `unicoin_product_service`.`suppliers` (`SUPPLIER_NAME`, `SUPPLIER_CODE`, `PHONE_NUMBER`, `EMAIL`, `ADDRESS`, `UPDATE_USER`, `status`) VALUES ('LEVI\'S','LVS', '012345678', 'levis@gmail.com', 'Anh', 1, 1);
INSERT INTO `unicoin_product_service`.`suppliers` (`SUPPLIER_NAME`, `SUPPLIER_CODE`, `PHONE_NUMBER`, `EMAIL`, `ADDRESS`, `UPDATE_USER`, `status`) VALUES ('Amazon', 'AMZ', '012345678', 'amazon@gmail.com', 'Mỹ', 1, 1);
INSERT INTO `unicoin_product_service`.`suppliers` (`SUPPLIER_NAME`, `SUPPLIER_CODE`, `PHONE_NUMBER`, `EMAIL`, `ADDRESS`, `UPDATE_USER`, `status`) VALUES ('Nike', 'NIK', '012345678', 'nike@gmail.com', 'Mỹ', 1, 1);
INSERT INTO `unicoin_product_service`.`suppliers` (`SUPPLIER_NAME`, `SUPPLIER_CODE`, `PHONE_NUMBER`, `EMAIL`, `ADDRESS`, `UPDATE_USER`, `status`) VALUES ('Adidas', 'ADS', '012345678', 'adidas@gmail.com', 'Đức', 1, 1);
